"use client";

import { useEffect, useState } from "react";
import { Loader2, RotateCw } from "lucide-react";
import { getRepoTour, type TourStep } from "@/lib/api";

export function CodebaseTour({ repoId }: { repoId: string }) {
  const [steps, setSteps] = useState<TourStep[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  function load(refresh = false) {
    setLoading(true);
    setError(null);
    getRepoTour(repoId, refresh)
      .then((d) => setSteps(d.steps))
      .catch((e) => setError(e instanceof Error ? e.message : "Failed to load tour"))
      .finally(() => setLoading(false));
  }

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
    load();
  }, [repoId]);

  if (loading) {
    return (
      <div className="flex items-center gap-3 rounded-xl border border-[var(--hairline)] bg-[var(--surface-card)] p-6 font-mono text-[13px] text-[var(--muted)]">
        <Loader2 className="size-4 animate-spin" strokeWidth={2} />
        generating tour with Ollama…
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded-xl border border-[var(--hairline)] bg-[var(--surface-card)] p-6">
        <p className="font-mono text-[13px] text-[#f87171]">{error}</p>
        <p className="mt-2 text-[13px] text-[var(--muted)]">
          The tour is generated by a local Ollama model. Make sure Ollama is
          running (<span className="font-mono">ollama serve</span>) and the model
          is pulled.
        </p>
        <button
          onClick={() => load(true)}
          className="mt-4 inline-flex h-9 items-center gap-2 rounded-md border border-[var(--hairline)] px-3.5 text-[13px] font-semibold text-[var(--ink)] hover:bg-[var(--surface-strong)]"
        >
          <RotateCw className="size-3.5" strokeWidth={2} />
          Retry
        </button>
      </div>
    );
  }

  return (
    <div>
      <div className="flex justify-end">
        <button
          onClick={() => load(true)}
          className="inline-flex h-8 items-center gap-1.5 rounded-md border border-[var(--hairline)] px-3 font-mono text-[11px] uppercase tracking-[0.12em] text-[var(--muted)] hover:text-[var(--ink)]"
        >
          <RotateCw className="size-3" strokeWidth={2} />
          Regenerate
        </button>
      </div>
      <ol className="mt-3 space-y-3">
        {steps?.map((s, i) => (
          <li
            key={i}
            className="rounded-xl border border-[var(--hairline)] bg-[var(--surface-card)] p-5"
          >
            <div className="flex items-baseline gap-3">
              <span className="font-mono text-[12px] text-[var(--accent)]">
                {String(i + 1).padStart(2, "0")}
              </span>
              <h3 className="display text-[17px] tracking-[-0.02em]">{s.title}</h3>
            </div>
            {s.path && (
              <div className="mt-1.5 pl-8 font-mono text-[12px] text-[var(--muted)]">
                {s.path}
              </div>
            )}
            <p className="mt-2 pl-8 text-[14px] leading-6 text-[var(--body)]">
              {s.explanation}
            </p>
          </li>
        ))}
      </ol>
    </div>
  );
}
