import ReactMarkdown from "react-markdown";

export function FinalReportCard({ report }: { report: string | null }) {
  return (
    <section className="border-t border-border pt-6">
      <div className="mb-5">
        <div className="font-mono text-[11px] uppercase tracking-[0.18em] text-zinc-500">
          Final report
        </div>
        <h2 className="mt-3 text-2xl font-semibold tracking-tight text-[#fafafa]">
          Engineering handoff
        </h2>
        <p className="mt-2 text-sm leading-7 text-zinc-500">
          Consolidated report generated by the backend workflow.
        </p>
      </div>

      {report ? (
        <div className="markdown-report max-w-none bg-[#0d0d0d] p-5 text-sm leading-7">
          <ReactMarkdown>{report}</ReactMarkdown>
        </div>
      ) : (
        <div className="py-6 text-sm text-zinc-500">
          Final report is not available yet.
        </div>
      )}
    </section>
  );
}
